### ISSUE TITLE
Breaking ui

### ISSUE THREAD

**Issue by halcion** [CustomNavigationbar/resources#13]
I started with compatibility mode because that is what the app suggests. The next thing that occurs is a blank white screen that says app is not compatible and the nav bar is left inoperable. The developer of the app couldn't be bothered with neither providing pertinent information on manually reverting the changes this app makes to secure settings of the OS nor letting the user know in advance the potential for the problems and what exactly that details so that they can make an informed decision on what exactly they would prefer to do in the likely event the device is in fact incompatible. To make matters worse, charging money on the playstore to essential break people's phones is absurd and yet that is what is happening by having this garbage released to the public.

**Comment by suphon-t** [comment]
What device are you on? The compatibility check reverts all changes done to your device in 30 seconds if you don't respond. And you can't say I'm charging money to break your phone because you need to get past the check in order to buy the app.
